site_name: jleclech blog
nav:
    - Home: 'index.md'
    - 'my_journey':
        - 'Journey': 'my_journey/journey.md'
    - About:
        - 'About': 'about.md'

extra_css:
    - css/autumn-theme.css
